@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.khazoda.plushables.item;

import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;