# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=2.0.4+1.21.1
group=com.khazoda.plushables
java_version=21

# Common
minecraft_version=1.21.1
mod_name=Plushables
mod_author=Khazoda
mod_id=plushables
mod_homepage=https://www.khazoda.com#plushables
mod_issues=https://github.com/Khazoda/Plushables/issues
license=GPL v3.0
credits=BumbleSculpts | Luke | MerchantPug
description=Bring cute plushies into your home
minecraft_version_range=[1.21.1, 1.22)

## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.1-20240808.144430
# https://parchmentmc.org/docs/getting-started#choose-a-version
parchment_minecraft=1.21
parchment_version=2024.11.10

# Fabric
fabric_version=0.109.0+1.21.1
fabric_loader_version=0.16.9
fabric_loader_minimum_version=0.15.0

# NeoForge
neoforge_version=21.1.80
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
