package com.khazoda.plushables.block.util;

import net.minecraft.core.Direction;
import net.minecraft.world.phys.shapes.Shapes;
import net.minecraft.world.phys.shapes.VoxelShape;

public class VoxelShapeHelper {

  /**
   * Takes an initial Direction, a target Direction and the VoxelShape data, and
   * returns a VoxelShape that's been rotated.
   * -
   * WARNING: Cache data generated by this method at Block instantiation,
   * otherwise it can cause a HUGE amount of frame lag.
   **/
  public static VoxelShape rotateShape(Direction from, Direction to, VoxelShape shape) {
    VoxelShape[] buffer = new VoxelShape[]{shape, Shapes.empty()};
    int times = (to.get2DDataValue() - from.get2DDataValue() + 4) % 4;
    for (int i = 0; i < times; i++) {
      buffer[0].forAllBoxes((minX, minY, minZ, maxX, maxY, maxZ) -> buffer[1] = Shapes.or(buffer[1],
          Shapes.create(1 - maxZ, minY, minX, 1 - minZ, maxY, maxX)));
      buffer[0] = buffer[1];
      buffer[1] = Shapes.empty();
    }
    return buffer[0];
  }

  /* Calculates all cardinally directed block shapes for caching */
  public static VoxelShape[] calculateBlockShapes(VoxelShape blockShape) {
    return new VoxelShape[]{
        blockShape,
        rotateShape(Direction.NORTH, Direction.EAST, blockShape),
        rotateShape(Direction.NORTH, Direction.SOUTH, blockShape),
        rotateShape(Direction.NORTH, Direction.WEST, blockShape)
    };
  }

  /* Used to abbreviate net.minecraft.block.AbstractBlock.getOutlineShape */
  public static VoxelShape getSidedOutlineShape(Direction direction, VoxelShape blockShape, VoxelShape[] blockShapes) {
    return switch (direction) {
      case NORTH -> blockShapes[0];
      case EAST -> blockShapes[1];
      case SOUTH -> blockShapes[2];
      case WEST -> blockShapes[3];
      default -> blockShape;
    };
  }
}
